### ISSUE TITLE
交换友链

### ISSUE THREAD

**Issue by wmathor** [LiZeC123/SmartTodo#1]
不好意思大佬，在这里给您留言，因为您博客的评论功能好像有问题
主要目的是想和您交换友链（我已添加您的友链）
link: https://wmathor.com/
name: mathor's blog

**Comment by LiZeC123** [comment]
@wmathor 你好, 很高兴和你交换友链, 我已经在源代码上加入了你的链接, 由于我最近用于发布博客的设备不在身边, 因此暂时无法更新到博客的页面上.  等过几天博客更新了, 我会再次通知你

我看到你的博客中关于申请友链的格式要求, 那么我的我的博客就大概是下面这样

link: https://lizec.top/
name:  LiZeC的博客

虽然看起来你的友链系统中并不能加入一个小标题, 但是我觉得我博客上作为小标题的这句Abstractness is the price of generality(普适的代价是抽象)   非常能概括软件设计和写博客文章过程中的取舍问题(以及我个人对于这些问题的态度), 所以要是能以某种方式加入那就更好了. (毕竟都是XXX的博客也看不出来啥)

> PS: 我觉得可以把小标题作为标题的一部分就可以了, 比如 `LiZeC的博客 - Abstractness is the price of generality`

-----------

博客的评论系统使用的是gitment, 不过这个项目太久没有维护了,  现在好像彻底不能用了. 我之后会换一个评论系统. 我目前考虑使用使用与gitment类似的gitalk作为替代方法, 不过这也许需要一段时间才能切换过来.

> PS: 很好奇你是如何发现我的博客的, 由于没有备案, 因此我的博客似乎不能被百度检索到. 虽然谷歌能检索到, 但是权重惨不忍睹,  除非关键词非常匹配, 否则基本也不能被发现, 我都要觉得自己的博客属于暗网了.

**Comment by wmathor** [comment]
@LiZeC123 已经修改好了
关于如何搜到您的博客，是这样的，我们马上要进行矩阵分析期末考试了（开卷，可以使用代码辅助验算）于是我就谷歌搜索sympy库在矩阵分析中的一些使用例子，结果就搜到了您的这篇文章[矩阵论简明笔记](https://lizec.top/2019/11/30/%E7%9F%A9%E9%98%B5%E8%AE%BA%E7%AE%80%E6%98%8E%E7%AC%94%E8%AE%B0/)，感觉写的不错，之后我就仔细看了下您博客的其它文章，发现您大概也是计算机的学生，同时估计也是做深度学习的，因此就xxxxxx

**Comment by LiZeC123** [comment]
@wmathor 原来如此.  能写代码辅助就真的太好了, 我们考试都是纯手算, 明明都已经会了, 但是计算能力不太行, 简直血亏.

---

关于友链,  我已经把你的链接加入到我们的博客页面上了, 你可以查看 https://lizec.top/about/ 

由于之前并没有太多人和我交换链接, 所以我并没有单独做一个页面, 而是直接放到了about页面上.  以后有空再修改一下吧.

博客的评论系统也已经切换到gitalk了, 现在应该能够正常评论了. 

---

我目前主要做的是自然语言处理相关的工作, 我看你好像也有不少关于自然语言处理的文章, 以后也可以在学术方面多多交流.

**Comment by wmathor** [comment]
😊

**Comment by wmathor** [comment]
大哥，我又来问你个问题了，就是我看你博客上有个slides，我想知道怎么做的，将ppt上传到博客。我网上搜了一下，利用reveal.js可以实现，但还是想问问你的是怎么实现的

**Comment by LiZeC123** [comment]
> 大哥，我又来问你个问题了，就是我看你博客上有个slides，我想知道怎么做的，将ppt上传到博客。我网上搜了一下，利用reveal.js可以实现，但还是想问问你的是怎么实现的

我用的是reveal.md 这样就能用Markdown的方式做PPT, 关于博客如何引入这个模块可以参考我之前的博客 

- https://lizec.top/2019/08/03/%E5%8D%9A%E5%AE%A2%E5%8A%A0%E5%85%A5%E6%96%B0%E7%9A%84%E6%A8%A1%E5%9D%97/

前期踩过一些坑, 基本上现有的类似项目里, 最简单好用的还是这个项目. 不过这个项目也有点小问题, 作者虽然提供了导出为PDF的功能, 但是基本上是残废的, 所以并不能导出. 如果以后你需要在没有网的环境用你的PPT, 可能就有点麻烦了.

**Comment by wmathor** [comment]
> > 大哥，我又来问你个问题了，就是我看你博客上有个slides，我想知道怎么做的，将ppt上传到博客。我网上搜了一下，利用reveal.js可以实现，但还是想问问你的是怎么实现的
> 
> 我用的是reveal.md 这样就能用Markdown的方式做PPT, 关于博客如何引入这个模块可以参考我之前的博客
> 
> * https://lizec.top/2019/08/03/%E5%8D%9A%E5%AE%A2%E5%8A%A0%E5%85%A5%E6%96%B0%E7%9A%84%E6%A8%A1%E5%9D%97/
> 
> 前期踩过一些坑, 基本上现有的类似项目里, 最简单好用的还是这个项目. 不过这个项目也有点小问题, 作者虽然提供了导出为PDF的功能, 但是基本上是残废的, 所以并不能导出. 如果以后你需要在没有网的环境用你的PPT, 可能就有点麻烦了.

ok，非常感谢，我看一看
